git stage ./change_name.sh
git stage ./Pipeline_scripts/False_Discovery_Analysis/Run_scripts/run_office_FD_test_unfilt.sh
git stage ./Pipeline_scripts/False_Discovery_Analysis/Run_scripts/run_goodrich_unfilt.sh
git stage ./Pipeline_scripts/False_Discovery_Analysis/Run_scripts/run_sw_sed_filt.sh
git stage ./Pipeline_scripts/False_Discovery_Analysis/Run_scripts/run_goodrich_filt.sh
git stage ./Pipeline_scripts/False_Discovery_Analysis/Run_scripts/run_office_FD_test_filt.sh
git stage ./Pipeline_scripts/False_Discovery_Analysis/Run_scripts/run_schubert_unfilt.sh
git stage ./Pipeline_scripts/False_Discovery_Analysis/Run_scripts/run_blueberry_filt.sh
git stage ./Pipeline_scripts/False_Discovery_Analysis/Run_scripts/run_arcticfresh_unfilt.sh
git stage ./Pipeline_scripts/False_Discovery_Analysis/Run_scripts/run_arcticfresh_filt.sh
git stage ./Pipeline_scripts/False_Discovery_Analysis/Run_scripts/run_hiv_noguera_unfilt.sh
git stage ./Pipeline_scripts/False_Discovery_Analysis/Run_scripts/run_hiv_noguera_filt.sh
git stage ./Pipeline_scripts/False_Discovery_Analysis/Run_scripts/run_JI_WTP_DS_filt.sh
git stage ./Pipeline_scripts/False_Discovery_Analysis/Run_scripts/run_sw_sed_unfilt.sh
git stage ./Pipeline_scripts/False_Discovery_Analysis/Run_scripts/run_schubert_filt.sh
git stage ./Pipeline_scripts/False_Discovery_Analysis/Run_scripts/run_blueberry_unfilt.sh
git stage ./Pipeline_scripts/False_Discovery_Analysis/Run_scripts/run_JI_WTP_DS_unfilt.sh
git stage ./Pipeline_scripts/Run_scripts/run_diarrhea_nonfilt.sh
git stage ./Pipeline_scripts/Run_scripts/run_obesity_nofilt.sh
git stage ./Pipeline_scripts/Run_scripts/FP_runs/run_hiv_noguera_filt.sh
git stage ./Pipeline_scripts/Run_scripts/FP_runs/run_hiv_noguera_unfilt_EXT.sh
git stage ./Pipeline_scripts/Run_scripts/FP_runs/run_JI_WTP_DS_unfilt_EXT.sh
git stage ./Pipeline_scripts/Run_scripts/FP_runs/run_sw_sed_filt.sh
git stage ./Pipeline_scripts/Run_scripts/FP_runs/run_blueberry_unfilt.sh
git stage ./Pipeline_scripts/Run_scripts/FP_runs/run_JI_WTP_DS_unfilt.sh
git stage ./Pipeline_scripts/Run_scripts/FP_runs/run_sw_sed_unfilt.sh
git stage ./Pipeline_scripts/Run_scripts/FP_runs/run_JI_WTP_DS_filt.sh
git stage ./Pipeline_scripts/Run_scripts/FP_runs/run_arcticfresh_unfilt_EXT.sh
git stage ./Pipeline_scripts/Run_scripts/FP_runs/run_schubert_filt.sh
git stage ./Pipeline_scripts/Run_scripts/FP_runs/run_sw_sed_unfilt_EXT.sh
git stage ./Pipeline_scripts/Run_scripts/FP_runs/run_blueberry_unfilt_EXT.sh
git stage ./Pipeline_scripts/Run_scripts/FP_runs/run_schubert_unfilt.sh
git stage ./Pipeline_scripts/Run_scripts/FP_runs/run_goodrich_unfilt_EXT.sh
git stage ./Pipeline_scripts/Run_scripts/FP_runs/run_blueberry_filt.sh
git stage ./Pipeline_scripts/Run_scripts/FP_runs/run_office_FD_test_unfilt_EXT.sh
git stage ./Pipeline_scripts/Run_scripts/FP_runs/run_hiv_noguera_unfilt.sh
git stage ./Pipeline_scripts/Run_scripts/FP_runs/run_arcticfresh_unfilt.sh
git stage ./Pipeline_scripts/Run_scripts/FP_runs/run_schubert_unfilt_EXT.sh
git stage ./Pipeline_scripts/Run_scripts/FP_runs/run_arcticfresh_filt.sh
git stage ./Pipeline_scripts/Run_scripts/FP_runs/run_goodrich_filt.sh
git stage ./Pipeline_scripts/Run_scripts/FP_runs/run_office_FD_test_unfilt.sh
git stage ./Pipeline_scripts/Run_scripts/FP_runs/run_office_FD_test_filt.sh
git stage ./Pipeline_scripts/Run_scripts/FP_runs/run_goodrich_unfilt.sh
git stage ./Pipeline_scripts/Run_scripts/run_subset_filt.sh
git stage ./Pipeline_scripts/Run_scripts/run_0.1_filt_datasets.sh
git stage ./Pipeline_scripts/Run_scripts/run_subset_no_filt.sh
git stage ./Pipeline_scripts/Run_scripts/run_obesity_filt.sh
git stage ./Pipeline_scripts/Run_scripts/run_no_filt_datasets.sh
git stage ./Pipeline_scripts/Run_scripts/run_diarrhea_filt.sh
