sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./change_name.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/False_Discovery_Analysis/Run_scripts/run_office_FD_test_unfilt.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/False_Discovery_Analysis/Run_scripts/run_goodrich_unfilt.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/False_Discovery_Analysis/Run_scripts/run_sw_sed_filt.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/False_Discovery_Analysis/Run_scripts/run_goodrich_filt.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/False_Discovery_Analysis/Run_scripts/run_office_FD_test_filt.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/False_Discovery_Analysis/Run_scripts/run_schubert_unfilt.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/False_Discovery_Analysis/Run_scripts/run_blueberry_filt.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/False_Discovery_Analysis/Run_scripts/run_arcticfresh_unfilt.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/False_Discovery_Analysis/Run_scripts/run_arcticfresh_filt.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/False_Discovery_Analysis/Run_scripts/run_hiv_noguera_unfilt.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/False_Discovery_Analysis/Run_scripts/run_hiv_noguera_filt.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/False_Discovery_Analysis/Run_scripts/run_JI_WTP_DS_filt.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/False_Discovery_Analysis/Run_scripts/run_sw_sed_unfilt.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/False_Discovery_Analysis/Run_scripts/run_schubert_filt.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/False_Discovery_Analysis/Run_scripts/run_blueberry_unfilt.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/False_Discovery_Analysis/Run_scripts/run_JI_WTP_DS_unfilt.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/Run_scripts/run_diarrhea_nonfilt.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/Run_scripts/run_obesity_nofilt.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/Run_scripts/FP_runs/run_hiv_noguera_filt.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/Run_scripts/FP_runs/run_hiv_noguera_unfilt_EXT.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/Run_scripts/FP_runs/run_JI_WTP_DS_unfilt_EXT.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/Run_scripts/FP_runs/run_sw_sed_filt.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/Run_scripts/FP_runs/run_blueberry_unfilt.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/Run_scripts/FP_runs/run_JI_WTP_DS_unfilt.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/Run_scripts/FP_runs/run_sw_sed_unfilt.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/Run_scripts/FP_runs/run_JI_WTP_DS_filt.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/Run_scripts/FP_runs/run_arcticfresh_unfilt_EXT.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/Run_scripts/FP_runs/run_schubert_filt.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/Run_scripts/FP_runs/run_sw_sed_unfilt_EXT.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/Run_scripts/FP_runs/run_blueberry_unfilt_EXT.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/Run_scripts/FP_runs/run_schubert_unfilt.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/Run_scripts/FP_runs/run_goodrich_unfilt_EXT.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/Run_scripts/FP_runs/run_blueberry_filt.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/Run_scripts/FP_runs/run_office_FD_test_unfilt_EXT.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/Run_scripts/FP_runs/run_hiv_noguera_unfilt.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/Run_scripts/FP_runs/run_arcticfresh_unfilt.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/Run_scripts/FP_runs/run_schubert_unfilt_EXT.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/Run_scripts/FP_runs/run_arcticfresh_filt.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/Run_scripts/FP_runs/run_goodrich_filt.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/Run_scripts/FP_runs/run_office_FD_test_unfilt.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/Run_scripts/FP_runs/run_office_FD_test_filt.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/Run_scripts/FP_runs/run_goodrich_unfilt.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/Run_scripts/run_subset_filt.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/Run_scripts/run_0.1_filt_datasets.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/Run_scripts/run_subset_no_filt.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/Run_scripts/run_obesity_filt.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/Run_scripts/run_no_filt_datasets.sh 
sed -i 's/Run_all_tools_fix2.sh/run_all_tools.sh/g' ./Pipeline_scripts/Run_scripts/run_diarrhea_filt.sh 
