---
title: "Figure3"
author: "Jacob T. Nearing"
date: "1/11/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(ggrepel)
library(cowplot)
```

#load in data
```{r}
filt_results <- readRDS("~/GitHub_Repos/Hackathon_testing/Data/Filt_results.RDS")
unfilt_results <- readRDS("~/GitHub_Repos/Hackathon_testing/Data/Unfilt_results.RDS")
```


## PCoA of Binary Distances for each tool
```{r}
## Start with filtered data
## We want to weight each dataset equally so we will take the mean the binary distance for all datasets for each tool

first_data = TRUE
for(dataset in filt_results){
  
  ### anything under 0.05 set to sig
  bin_dataset <- dataset[[2]]
  
  ## if significant set to 2
  bin_dataset[bin_dataset < 0.05] <- 2
  ## if not significant set to 0
  bin_dataset[bin_dataset != 2] <- 0
  ## if was significant set value to 1
  bin_dataset[bin_dataset==2] <- 1
  
  if(first_data){
    dataset_binary_dist <- dist(t(bin_dataset), method="binary")
    first_data <- F
  }else{
    dataset_binary_dist <- dataset_binary_dist + dist(t(bin_dataset), method="binary")
  }
  
}

dataset_binary_dist <- dataset_binary_dist/length(filt_results)

filt_pcoa <- cmdscale(d=dataset_binary_dist, k=5, eig=T)

eig_percent <- filt_pcoa$eig*100/sum(filt_pcoa$eig) 
eig_percent
barplot(eig_percent)

PC1_set <- paste("PC1 (", as.character(round(eig_percent[1],3)), "%)", sep="")
PC2_set <- paste("PC2 (", as.character(round(eig_percent[2],3)), "%)", sep="")
PC3_set <- paste("PC3 (", as.character(round(eig_percent[3],3)), "%)", sep="")


coords <- filt_pcoa$points
## try ggord.

plot_data_filt <- data.frame(PC1=coords[,1], PC2=coords[,2], PC3=coords[,3])


## fix tool names
tool_names <- c(aldex2="ALDEx2", ancom="ANCOM", corncob="Corncob", deseq2="DESeq2", edger="edgeR", lefse="LEfSe", 
                limma_voom_TMM="Limma Voom TMM", limma_voom_TMMwsp="Limma Voom TMMwsp", maaslin2="MaAsLin2",
                maaslin2rare="MaAsLin2 Rarified", metagenomeSeq="metagenomeSeq", ttestrare="T-test Rarified", 
                wilcoxonclr="Wilcoxon CLR", wilcoxonrare="Wilcoxon Rarified")

plot_data_filt$Tool <- tool_names[rownames(plot_data_filt)]


plot12 <- ggplot(plot_data_filt, aes(x=PC1, y=PC2, label=Tool)) + geom_point() + coord_fixed() +
  xlab(PC1_set) + ylab(PC2_set) + geom_text_repel() + theme_bw() +
  theme(text = element_text(size=16, color="black"), axis.text = element_text(color="black")) +
  ggtitle("Filtered")
plot12

plot13 <- ggplot(plot_data_filt, aes(x=PC1, y=PC3, label=Tool)) + geom_point() + coord_fixed() +
  xlab(PC1_set) + ylab(PC3_set) + geom_text_repel() + theme_bw() +
  theme(text = element_text(size=16, color="black"), axis.text = element_text(color="black"))
plot13

plot23 <- ggplot(plot_data_filt, aes(x=PC2, y=PC3, label=Tool)) + geom_point() + coord_fixed() +
  xlab(PC2_set) + ylab(PC3_set) + geom_text_repel() + theme_bw() +
  theme(text = element_text(size=16, color="black"), axis.text = element_text(color="black"))
plot23
```



```{r}
first_data = TRUE

## need to remove dataset where one tool didn't finish.
No_FreshWater_Adj_p_tabs_unfilt <- unfilt_results
No_FreshWater_Adj_p_tabs_unfilt[[2]] <- NULL

for(dataset in No_FreshWater_Adj_p_tabs_unfilt){
  
  ### anything under 0.05 set to sig
  bin_dataset <- dataset[[2]]
  
  ## if significant set to 2
  bin_dataset[bin_dataset < 0.05] <- 2
  ## if not significant set to 0
  bin_dataset[bin_dataset != 2] <- 0
  ## if was significant set value to 1
  bin_dataset[bin_dataset==2] <- 1
  
  if(first_data){
    dataset_binary_dist_unfilt <- dist(t(bin_dataset), method="binary")
    first_data <- F
  }else{
    dataset_binary_dist_unfilt <- dataset_binary_dist_unfilt + dist(t(bin_dataset), method="binary")
  }
  
}

dataset_binary_dist_unfilt <- dataset_binary_dist_unfilt/37

unfilt_pcoa <- cmdscale(d=dataset_binary_dist_unfilt, k=5, eig=T)

eig_percent_unfilt <- unfilt_pcoa$eig*100/sum(unfilt_pcoa$eig) 
eig_percent_unfilt
barplot(eig_percent_unfilt)

PC1_set_unfilt <- paste("PC1 (", as.character(round(eig_percent_unfilt[1],3)), "%)", sep="")
PC2_set_unfilt <- paste("PC2 (", as.character(round(eig_percent_unfilt[2],3)), "%)", sep="")
PC3_set_unfilt <- paste("PC3 (", as.character(round(eig_percent_unfilt[3],3)), "%)", sep="")


coords_unfilt <- unfilt_pcoa$points
## try ggord.

plot_data_unfilt <- data.frame(PC1=coords_unfilt[,1], PC2=coords_unfilt[,2], PC3=coords_unfilt[,3])


## fix tool names
plot_data_unfilt$Tool <- tool_names[rownames(plot_data_unfilt)]


plot12_unfilt <- ggplot(plot_data_unfilt, aes(x=PC1, y=PC2, label=Tool)) + geom_point() + coord_fixed() +
  xlab(PC1_set_unfilt) + ylab(PC2_set_unfilt) + geom_text_repel() + theme_bw() +
  theme(text = element_text(size=16, color="black"), axis.text = element_text(color="black")) +
  ggtitle("Unfiltered")
plot12_unfilt

Final_figure3 <- plot_grid(plot12_unfilt, plot12, labels = c("A", "B"))
Final_figure3

```